####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |       ______                         _   _             _    _                                | #
# |      |  ____|        /\             | | (_)           | |  | |                               | #
# |      | |____      __/  \  _   _  ___| |_ _  ___  _ __ | |__| | ___  _   _ ___  ___           | #
# |      |  __\ \ /\ / / /\ \| | | |/ __| __| |/ _ \| '_ \|  __  |/ _ \| | | / __|/ _ \          | #
# |      | |   \ V  V / ____ \ |_| | (__| |_| | (_) | | | | |  | | (_) | |_| \__ \  __/          | #
# |      |_|    \_/\_/_/    \_\__,_|\___|\__|_|\___/|_| |_|_|  |_|\___/ \__,_|___/\___|          | #
# |                                                                                              | #
# |                                     Made by: Kaotich00                                       | #
# |                                                                                              | #
# |                   SOURCE CODE: https://github.com/ForgottenWorld/FwAuctionHouse              | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'database'

# Admin Credentials for the database.
username: 'username'
password: 'password'

webApiKey: '12345678901234567890123456789012'
webApiHost: 'localhost'
webApiPort: '8080'